### ISSUE TITLE
[Feature Request] Paste image from clipboard

### ISSUE THREAD

**Issue by mac2000** [WellDoneCode/perfectpixel#47]
It is possible to catch pasted images in google chrome and then display them as base64.

http://stackoverflow.com/questions/6333814/how-does-the-paste-image-from-clipboard-functionality-work-in-gmail-and-google-c

It will be very nice if there will be ability not only add layer from file but also paste it from clipboard.

For example if I just want to check some little part of page, I can copy it with my snipping tool and paste on to page I'm working on without need to save any files.

I think it will be huge time saver.

**Comment by abelozerov** [comment]
Resolved
