### ISSUE TITLE
Interference with certain <select> and <textarea> elements

### ISSUE THREAD

**Issue by dresb** [WellDoneCode/perfectpixel#56]
I found out the extension to inline certain \<select\> and \<textarea\> elements in websites where they are nested inside a \<label\> tag.

I believe this commit solves the issue: https://github.com/dresb/perfectpixel/commit/f38239c686d20af0473dd47e793135a2cac995d0
The relevant change is in line 87, the rest are just automated trailing whitespace cleanups.

**Comment by abelozerov** [comment]
Hi @dresb Thank you very much for bugfix. Can you please add it also as pull request?
