### ISSUE TITLE
If Chrome's device mode is enabled you can't drag the overlay neither PP dialog box

### ISSUE THREAD

**Issue by ramon-v** [WellDoneCode/perfectpixel#58]
If you enable Chrome's device mode and choose any of device's options instead of notebook's options, you can't drag the overlay image neither the PerfectPixel's dialog box.

**Comment by kroleg** [comment]
Disable touch emulation and drag will work
15 янв. 2015 г. 3:45 пользователь "Ramon Vasconcelos" <
notifications@github.com> написал:

**Comment by abelozerov** [comment]
Fixed in 1.75 (after you reload page after enabling device mode)
