### ISSUE TITLE
Suggestion: In device mode, put "PerfectPixel" box outside of page. (like dev tools does)

### ISSUE THREAD

**Issue by centure** [WellDoneCode/perfectpixel#60]

**Comment by abelozerov** [comment]
It's not possible to put outside page unfortunately, but in latest version 1.75 drag-n-drop works in device mode (after page reload after enabling device mode), also panel is automatically collapsed when opened in device mode

**Comment by centure** [comment]
ha, i see. unfortunately indeed, thanks for replying!
