### ISSUE TITLE
Layer rename

### ISSUE THREAD

**Issue by GoshaEgorian** [WellDoneCode/perfectpixel#67]
A year ago there was a future to name/rename any layer, but now it doesn't work. I cannot find a hotkey for this or something alse about it. So what's way to do it now? Does it work?

**Comment by abelozerov** [comment]
Hi, yes, it was removed because almost nobody used it

**Comment by GoshaEgorian** [comment]
But I did...
Well, anyway, thanks! :)

**Comment by abelozerov** [comment]
Yes, I see, sorry for that. What do you think if part of file name will be presented near layer thumbnail, will it be helpful for your case?

**Comment by abelozerov** [comment]
File name now presented on top of layer thumbnail, do you think it cover the issue?

**Comment by GoshaEgorian** [comment]
Yes, it's very useful, thank you a lot!
